// angular/openProject/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'openProject';
  public pokeUrl = undefined ;
  public firstGenPokemonIdsBody = undefined ;
  public firstGenPokeDetails :  any[];
  // public doc: string = "";


    public docTest(): void {
      const fetchFirstGenPokemons = async () => {
        const firstGenPokemonIdsResponse = await fetch('https://pokeapi.co/api/v2/type/8/');
        const firstGenPokemonIdsBody = await firstGenPokemonIdsResponse.json();
        this.pokeUrl = firstGenPokemonIdsBody.pokemon;

         const firstGenPokemonDetails = await Promise.all(
          firstGenPokemonIdsBody.pokemon.map(async (p: any) => {
            const pDetails = await fetch(p.pokemon.url);


            return await pDetails.json();
          })
         );
      this.firstGenPokeDetails = firstGenPokemonDetails;
      };
      fetchFirstGenPokemons();

      // const firstGenPokemonIdsBody = "undefined" ;
      // fetch('https://pokeapi.co/api/v2/type/8/')
      // .then(response =>  response.json())
      // .then(body => {this.firstGenPokemonIdsBody = body;
      //   this.pokeUrl = body.pokemon;
      // });

      // firstGenPokemonIdsBody.pokemon.map( (p) =>{
      //   fetch(p.pokemon.url)
      //   .then(body => );
      //   return await pDetails.json();
      //
      // })



    }
  }

<p>hola</p>
<h1>{{title}}</h1>
<app-art-work></app-art-work>
<div>
{{docTest()}}
<!-- {{pokeUrl}} -->
</div>
<div style = "column-count:4;">
  <ul *ngFor = "let item of firstGenPokeDetails" >
  <div style =  "backgroundColor: purple; color: white;height: 310px;break-inside: avoid;">
    <p>hola</p>
    como se encuentrs {{item.name}}
    <!-- <img src= "{{item.sprites.front_default}}" > -->
  </div>
  </ul>
</div>

// react/my_react/src/App.js
import './App.css';
import React,{ useState, useEffect } from 'react';

const firstGenPokemonPath = 'https://pokeapi.co/api/v2/type/13/';
function App(){

  const [firstGenPokemonDetails, setfirstGenPokemonDetails] = useState([]);
  const [pokemonurl,setpokemonurl] = useState([]);
  const [test,setTest] = useState(['test']);
  // const listItems = firstGenPokemonDetails.map(( i ) =>
  //   <div id = "pokeDiv">{i.name} </div> );
// text added

  useEffect(() => {
    const fetchFirstGenPokemons = async () => {
      const firstGenPokemonIdsResponse = await fetch(firstGenPokemonPath);
      const firstGenPokemonIdsBody = await firstGenPokemonIdsResponse.json();
      setpokemonurl(firstGenPokemonIdsBody.pokemon);

      const firstGenPokemonDetails = await Promise.all(
        firstGenPokemonIdsBody.pokemon.map(async (p) => {
          var pDetails = await fetch(p.pokemon.url);


          return await pDetails.json();
        })
      );

      setfirstGenPokemonDetails(firstGenPokemonDetails);

    };

    fetchFirstGenPokemons();

  }, []);


  return (

    <div>

<h2 style = {{textAlign: "center"}}>  pokemon! </h2>


      <div id = 'pokeContainer'> <ul id = 'listStyle'>
      {firstGenPokemonDetails.map((i) => <div id = "pokeDiv">
      <p style={{color: "white", marginTop: "0px"}}>{i.name} </p>
      <img src={i.sprites.front_default} alt="Logo" id= "pokeImage"/> </div>)} </ul>


      </div>





    </div>



  );
}



export default App;
